---
- hosts: teste
  tasks:
    - name: "Criar Backup"
      routeros_command:
        commands: /system script add name="BACKUP CLIENTES" source=":local FTPServer \"??????\"\
                  \n:local FTPPort 21\
                  \n:local FTPUser \"?????\"\
                  \n:local FTPPass \"???????\"\
                  \n/export file=([/system identity get name] . \"-\" . [:pick [/system clock \
                  get date] 4 6] . [:pick [/system clock get date] 0 3] . [:pick [/system cloc\
                  k get date] 7 11]);\
                  \n/tool fetch address=\$FTPServer src-path=([/system identity get name] . \"\
                  -\" . [:pick [/system clock get date] 4 6] . [:pick [/system clock get date]\
                  \_0 3] . [:pick [/system clock get date] 7 11].\".rsc\") user=\$FTPUser mode\
                  =ftp password=\$FTPPass upload=yes dst-path=([/system identity get name] . \
                  \"-\" . [:pick [/system clock get date] 4 6] . [:pick [/system clock get dat\
                  e] 0 3] . [:pick [/system clock get date] 7 11].\".rsc\");\
                  \n:delay 10s\
                  \n:delay 300s\
                  \n/file remove [find where type=backup];\
                  \n/file remove [find where type=script];\
                  \n:foreach i in=[/file find] do={:if ([:typeof [:find [/file get \$i name] \
                  \".rsc\"]]!=\"nil\") do={/file remove \$i}};\
                  \n:foreach i in=[/file find] do={:if ([:typeof [:find [/file get \$i name] \
                  \".backup\"]]!=\"nil\") do={/file remove \$i}};"
    - name: "Rodar backup"
      routeros_command:
        commands: system script run 0
